language: go

os:
  - linux
  - osx

go:
  - tip
  - "1.10"
  - 1.9
  - 1.8

install:
  - go get github.com/issue9/assert
  - go get github.com/dimfeld/httptreemux
  - go get github.com/pressly/chi

script: go test -race -v ./...
