language: go

go:
    - tip
    - 1.8

install:
    - go get github.com/issue9/assert
    - go get github.com/dimfeld/httptreemux
    - go get github.com/pressly/chi

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)